### ISSUE TITLE
为你打call

### ISSUE THREAD

**Issue by ilcamf** [DuanMengyan/Graduation-Project#1]
加油，你好厉害的样子，我也是一个点云初学者，我也照着你的程序，自己搭建了一个界面，但最近老是让握做边界提取，请问，除了pcl中的边界提取，您还实现过其他的算法吗？谢谢，谢谢，谢谢。

**Comment by Mengyanduan** [comment]
我的毕设中主要是提取油菜叶片边缘轮廓特征，主要参考了一篇文献，实现了提取边界的算法，其实这个算法对于类似平面的边界提取效果挺好的，工程中有相关代码。其他算法暂时没有实现了。

**Comment by ilcamf** [comment]
请问，我能阅读一下你所实现的那个边界提取算法的文献嘛！谢谢，

**Comment by Mengyanduan** [comment]
已发送至邮箱，请注意查收。

**Comment by ilcamf** [comment]
没有文章呢，谢谢

在 2018-06-15 19:19:22，"DuanMengyan" <notifications@github.com> 写道：


已发送至邮箱，请注意查收。
